Repository BYTE-ADMU/itech-ui, pull requests merged in 2021-03, with the labels that each got.

#51 Discover Page
  src/assets/img/search-vector.svg
  src/components/Navbar.vue
  src/main.js
  src/pages/Discover.vue
Labels: enhancement

#54 Landing Page #53
  src/assets/img/unauth/index/section1-botWelcome.svg
  src/assets/img/unauth/index/section2-botWelcome.svg
  src/components/Navbar.vue
  src/components/unauth/index/section1.vue
  src/components/unauth/index/section2-slides/ArticleButton.vue
  src/components/unauth/index/section2-slides/CourseButton.vue
  src/components/unauth/index/section2-slides/Slide.vue
  src/components/unauth/index/section2-slides/Slides.vue
  src/components/unauth/index/section2.vue
  src/components/unauth/index/section3.vue
  src/layouts/Default.vue
  src/pages/Index.vue
  src/pages/articles/[id].vue
  src/pages/courses/[id].vue
  src/pages/topics/[id].vue
  tailwind.config.js
Labels: enhancement

#63 Landing Page #53 (2)
  src/assets/img/unauth/index/section1-botWelcome.svg
  src/assets/img/unauth/index/section2-botWelcome.svg
  src/components/Navbar.vue
  src/components/unauth/index/section1.vue
  src/components/unauth/index/section2-slides/ArticleButton.vue
  src/components/unauth/index/section2-slides/CourseButton.vue
  src/components/unauth/index/section2-slides/Slide.vue
  src/components/unauth/index/section2-slides/Slides.vue
  src/components/unauth/index/section2.vue
  src/components/unauth/index/section3.vue
  src/layouts/Default.vue
  src/pages/Index.vue
  src/pages/articles/[id].vue
  src/pages/courses/[id].vue
  src/pages/topics/[id].vue
  tailwind.config.js
Labels: enhancement

#60 Footer Revamp #59
  src/components/Footer.vue
Labels: enhancement

#56 Topics Page Revamp #55
  src/components/auth/topics/cover.vue
  src/pages/topics/[id].vue
Labels: enhancement

#64 Register Page Function #24
  src/components/unauth/register/Tabs.vue
  src/store/modules/userStore.js
Labels: enhancement

#58 Courses Page Revamp #57
  src/components/auth/courses/cover.vue
  src/pages/courses/[id].vue
Labels: enhancement

#65 Dashboard Page Revamp #44
  src/components/auth/dashboard/bitbotFeature.vue
  src/components/auth/dashboard/featureEntry.vue
  src/pages/Dashboard.vue
Labels: enhancement

#68 ITECH Phase 2 Sprint 2
  src/assets/img/search-vector.svg
  src/assets/img/unauth/index/section1-botWelcome.svg
  src/assets/img/unauth/index/section2-botWelcome.svg
  src/components/Footer.vue
  src/components/Navbar.vue
  src/components/auth/courses/cover.vue
  src/components/auth/dashboard/bitbotFeature.vue
  src/components/auth/dashboard/featureEntry.vue
  src/components/auth/topics/cover.vue
  src/components/unauth/index/section1.vue
  src/components/unauth/index/section2-slides/ArticleButton.vue
  src/components/unauth/index/section2-slides/CourseButton.vue
  src/components/unauth/index/section2-slides/Slide.vue
  src/components/unauth/index/section2-slides/Slides.vue
  src/components/unauth/index/section2.vue
  src/components/unauth/index/section3.vue
  src/components/unauth/register/Tabs.vue
  src/layouts/Default.vue
  src/main.js
  src/pages/Categories/Hacker.vue
  src/pages/Categories/Hipster.vue
  src/pages/Categories/Hustler.vue
  src/pages/Dashboard.vue
  src/pages/Discover.vue
  src/pages/Index.vue
  src/pages/Login.vue
  src/pages/articles/[id].vue
  src/pages/courses/[id].vue
  src/pages/topics/[id].vue
  src/store/modules/userStore.js
  tailwind.config.js
Labels: enhancement

#72 404 Not Found Page #71
  src/assets/img/404.svg
  src/assets/img/404mobile.svg
  src/pages/404.vue
Labels: enhancement

#76 Animations #73
  src/components/Footer.vue
  src/components/auth/articles/ArticleButtonCard.vue
  src/components/auth/articles/CommentSection.vue
  src/components/auth/dashboard/articleEntry.vue
  src/components/auth/dashboard/bitbotFeature.vue
  src/components/auth/dashboard/featureEntry.vue
  src/components/auth/dashboard/playlistEntry.vue
  src/components/unauth/index/section2-slides/ArticleButton.vue
  src/components/unauth/index/section2-slides/CourseButton.vue
  src/components/unauth/index/section2-slides/Slide.vue
  src/layouts/Default.vue
  src/pages/Categories/Hipster.vue
  src/pages/Categories/Hustler.vue
  src/pages/Discover.vue
  src/pages/articles/[id].vue
  src/pages/courses/[id].vue
  src/pages/topics/[id].vue
Labels: enhancement, ⭐ ALL GOODS WITH THIS UwU ⭐

#70 Register Page Responsiveness #69
  src/assets/img/unauth/register/icons/coursedropdown.svg
  src/assets/img/unauth/register/icons/yeardropdown.svg
  src/components/unauth/register/Tabs.vue
  src/pages/Login.vue
  src/pages/forgotpassword.vue
  src/pages/register.vue
Labels: enhancement, ⭐ ALL GOODS WITH THIS UwU ⭐

#79 About Page #74
  src/assets/img/unauth/about/section1bg.svg
  src/assets/img/unauth/about/section3bg.svg
  src/assets/img/unauth/about/section3bytelogo.svg
  src/assets/img/unauth/about/section4-pic1.png
  src/assets/img/unauth/about/section4-pic2.png
  src/components/Footer.vue
  src/components/unauth/about/Section1.vue
  src/components/unauth/about/Section2.vue
  src/components/unauth/about/Section3.vue
  src/components/unauth/about/Section4.vue
  src/components/unauth/about/Track.vue
  src/pages/About.vue
  tailwind.config.js
Labels: enhancement, ⭐ ALL GOODS WITH THIS UwU ⭐

#81 Navbar Revamp #75
  gridsome.server.js
  src/assets/img/icons/CloseIcon.svg
  src/assets/img/icons/DefaultUserIcon.svg
  src/assets/img/icons/MenuIcon.svg
  src/assets/img/icons/UserAccount.svg
  src/components/Navbar.vue
  src/components/auth/categories/cover.vue
  src/components/auth/courses/cover.vue
  src/components/auth/dashboard/articleEntry.vue
  src/components/auth/topics/cover.vue
  src/layouts/Default.vue
  src/main.js
  src/pages/Categories/Hacker.vue
  src/pages/Categories/Hipster.vue
  src/pages/Categories/Hustler.vue
  src/pages/Discover.vue
  src/pages/articles/[id].vue
  src/pages/courses/[id].vue
  src/pages/topics/[id].vue
  src/store/modules/userStore.js
Labels: enhancement, ⭐ ALL GOODS WITH THIS UwU ⭐

#82 ITECH Phase 2 Sprint 3
  gridsome.server.js
  src/assets/img/404.svg
  src/assets/img/404mobile.svg
  src/assets/img/icons/CloseIcon.svg
  src/assets/img/icons/DefaultUserIcon.svg
  src/assets/img/icons/MenuIcon.svg
  src/assets/img/icons/UserAccount.svg
  src/assets/img/unauth/about/section1bg.svg
  src/assets/img/unauth/about/section3bg.svg
  src/assets/img/unauth/about/section3bytelogo.svg
  src/assets/img/unauth/about/section4-pic1.png
  src/assets/img/unauth/about/section4-pic2.png
  src/assets/img/unauth/register/icons/coursedropdown.svg
  src/assets/img/unauth/register/icons/yeardropdown.svg
  src/components/Footer.vue
  src/components/Loader.vue
  src/components/Navbar.vue
  src/components/NavbarMobile.vue
  src/components/SearchBar.vue
  src/components/auth/articles/ArticleButtonCard.vue
  src/components/auth/articles/CommentSection.vue
  src/components/auth/categories/cover.vue
  src/components/auth/courses/cover.vue
  src/components/auth/dashboard/articleEntry.vue
  src/components/auth/dashboard/bitbotFeature.vue
  src/components/auth/dashboard/featureEntry.vue
  src/components/auth/dashboard/playlistEntry.vue
  src/components/auth/topics/cover.vue
  src/components/unauth/about/Section1.vue
  src/components/unauth/about/Section2.vue
  src/components/unauth/about/Section3.vue
  src/components/unauth/about/Section4.vue
  src/components/unauth/about/Track.vue
  src/components/unauth/index/section2-slides/ArticleButton.vue
  src/components/unauth/index/section2-slides/CourseButton.vue
  src/components/unauth/index/section2-slides/Slide.vue
  src/components/unauth/register/Tabs.vue
  src/layouts/Default.vue
  src/main.js
  src/pages/404.vue
  src/pages/About.vue
  src/pages/Categories/Hacker.vue
  src/pages/Categories/Hipster.vue
  src/pages/Categories/Hustler.vue
  src/pages/Discover.vue
  src/pages/Login.vue
  src/pages/articles/[id].vue
  src/pages/courses/[id].vue
  src/pages/forgotpassword.vue
  src/pages/register.vue
  src/pages/topics/[id].vue
  src/store/modules/userStore.js
  tailwind.config.js
Labels: enhancement, ⌛ REVIEWING OwO ⌛

#83 Modals #77
  src/assets/img/unauth/close-modal-vector.svg
  src/components/Navbar.vue
  src/components/loggingInModal.vue
  src/components/successfulLoginModal.vue
  src/components/successfulLogoutModal.vue
  src/components/unauth/register/Tabs.vue
  src/components/unauth/register/registerModal.vue
  src/components/unauth/unauthModal.vue
  src/main.js
  src/pages/Categories/Hacker.vue
  src/pages/Categories/Hipster.vue
  src/pages/Dashboard.vue
  src/pages/Discover.vue
  src/pages/Login.vue
  src/pages/articles/[id].vue
  src/pages/courses/[id].vue
Labels: enhancement, ⭐ ALL GOODS WITH THIS UwU ⭐

#86 Register Course Select #85
  src/components/unauth/register/Tabs.vue
  src/components/unauth/register/courses.vue
  src/layouts/Default.vue
  src/store/index.js
  src/store/modules/admuCoursesStore.js
Labels: enhancement, ⭐ ALL GOODS WITH THIS UwU ⭐

#84 User Profile Page #78
  src/assets/img/icons/editIcon.png
  src/components/Navbar.vue
  src/components/auth/dashboard/bitbotFeature.vue
  src/components/auth/userprofile/courses.vue
  src/components/auth/userprofile/cover.vue
  src/components/auth/userprofile/updatingModal.vue
  src/components/unauth/register/Tabs.vue
  src/main.js
  src/pages/Dashboard.vue
  src/pages/Discover.vue
  src/pages/Login.vue
  src/pages/UserProfile.vue
  src/store/modules/userStore.js
Labels: enhancement, ⭐ ALL GOODS WITH THIS UwU ⭐

#92 My List + Booking System for Articles and Courses #89
  src/assets/img/icons/BookmarkWhite.svg
  src/components/Navbar.vue
  src/components/NavbarMobile.vue
  src/components/auth/courses/cover.vue
  src/components/auth/mylist/cover.vue
  src/main.js
  src/pages/Dashboard.vue
  src/pages/User/Account.vue
  src/pages/User/SavedList.vue
  src/pages/articles/[id].vue
  src/pages/courses/[id].vue
  src/store/modules/userStore.js
Labels: enhancement, ⭐ ALL GOODS WITH THIS UwU ⭐

#94 Meet The Team Page #87
  src/assets/img/unauth/meetTheTeam/BB3-1.png
  src/assets/img/unauth/meetTheTeam/BB3-1mobile.png
  src/assets/img/unauth/meetTheTeam/BB3-2.png
  src/assets/img/unauth/meetTheTeam/BB3-2mobile.png
  src/assets/img/unauth/meetTheTeam/BB3-3.png
  src/assets/img/unauth/meetTheTeam/BB3-3mobile.png
  src/assets/img/unauth/meetTheTeam/BB3.png
  src/assets/img/unauth/meetTheTeam/BB3mobile.png
  src/assets/img/unauth/meetTheTeam/bottom-confetti.png
  src/assets/img/unauth/meetTheTeam/meet-confetti.png
  src/assets/img/unauth/meetTheTeam/top-confetti.png
  src/components/Footer.vue
  src/components/unauth/meetTheTeam/cover.vue
  src/components/unauth/meetTheTeam/coverMobile.vue
  src/components/unauth/meetTheTeam/teamMemberCard.vue
  src/layouts/Default.vue
  src/pages/MeetTheTeam.vue
  src/store/index.js
  src/store/modules/itechStore.js
Labels: enhancement, ⭐ ALL GOODS WITH THIS UwU ⭐

#93 Articles Comment System #88
  package-lock.json
  package.json
  src/assets/img/icons/BookmarkWhite.svg
  src/assets/img/icons/editIcon.png
  src/assets/img/unauth/close-modal-vector.svg
  src/components/Navbar.vue
  src/components/NavbarMobile.vue
  src/components/SearchBar.vue
  src/components/auth/articles/CommentCard.vue
  src/components/auth/articles/CommentSection.vue
  src/components/auth/articles/ProcessedMarkdown.vue
  src/components/auth/courses/cover.vue
  src/components/auth/dashboard/articleEntry.vue
  src/components/auth/dashboard/bitbotFeature.vue
  src/components/auth/dashboard/featureEntry.vue
  src/components/auth/dashboard/playlistEntry.vue
  src/components/auth/mylist/cover.vue
  src/components/auth/userprofile/courses.vue
  src/components/auth/userprofile/cover.vue
  src/components/auth/userprofile/updatingModal.vue
  src/components/loggingInModal.vue
  src/components/successfulLoginModal.vue
  src/components/successfulLogoutModal.vue
  src/components/unauth/about/Track.vue
  src/components/unauth/index/section2-slides/Slide.vue
  src/components/unauth/index/section2-slides/Slides.vue
  src/components/unauth/register/Tabs.vue
  src/components/unauth/register/courses.vue
  src/components/unauth/register/registerModal.vue
  src/components/unauth/unauthModal.vue
  src/layouts/Default.vue
  src/main.js
  src/pages/Categories/Hacker.vue
  src/pages/Categories/Hipster.vue
  src/pages/Categories/Hustler.vue
  src/pages/Dashboard.vue
  src/pages/Discover.vue
  src/pages/Login.vue
  src/pages/User/Account.vue
  src/pages/User/SavedList.vue
  src/pages/articles/[id].vue
  src/pages/courses/[id].vue
  src/pages/topics/[id].vue
  src/store/index.js
  src/store/modules/admuCoursesStore.js
  src/store/modules/articlesStore.js
  src/store/modules/coursesStore.js
  src/store/modules/topicsStore.js
  src/store/modules/userStore.js
  yarn.lock
Labels: enhancement, ⭐ ALL GOODS WITH THIS UwU ⭐

#96 ITECH Phase 2 Sprint 4
  src/assets/img/unauth/meetTheTeam/BB3-1.png
  src/assets/img/unauth/meetTheTeam/BB3-1mobile.png
  src/assets/img/unauth/meetTheTeam/BB3-2.png
  src/assets/img/unauth/meetTheTeam/BB3-2mobile.png
  src/assets/img/unauth/meetTheTeam/BB3-3.png
  src/assets/img/unauth/meetTheTeam/BB3-3mobile.png
  src/assets/img/unauth/meetTheTeam/BB3.png
  src/assets/img/unauth/meetTheTeam/BB3mobile.png
  src/assets/img/unauth/meetTheTeam/bottom-confetti.png
  src/assets/img/unauth/meetTheTeam/meet-confetti.png
  src/assets/img/unauth/meetTheTeam/top-confetti.png
  src/components/Footer.vue
  src/components/unauth/meetTheTeam/cover.vue
  src/components/unauth/meetTheTeam/coverMobile.vue
  src/components/unauth/meetTheTeam/teamMemberCard.vue
  src/layouts/Default.vue
  src/pages/MeetTheTeam.vue
  src/store/index.js
  src/store/modules/itechStore.js
Labels: enhancement

#97 Titia Hotfix 1
  package-lock.json
  src/assets/img/unauth/index/section2/slides/HACKER-bg.png
  src/assets/img/unauth/index/section2/slides/HIPSTER-bg.png
  src/assets/img/unauth/index/section2/slides/HUSTLER-bg.png
  src/components/auth/courses/cover.vue
  src/components/auth/courses/coverPlaceholder.vue
  src/components/auth/dashboard/articleEntry.vue
  src/components/auth/dashboard/articlePlaceholder.vue
  src/components/auth/dashboard/coursesPlaceholder.vue
  src/components/auth/dashboard/featureEntry.vue
  src/components/auth/dashboard/playlistEntry.vue
  src/components/unauth/index/section2-slides/Slide.vue
  src/components/unauth/meetTheTeam/teamMemberPlaceholder.vue
  src/components/unauth/unauthBookmarkModal.vue
  src/pages/Categories/Hacker.vue
  src/pages/Categories/Hipster.vue
  src/pages/Categories/Hustler.vue
  src/pages/Dashboard.vue
  src/pages/Discover.vue
  src/pages/Login.vue
  src/pages/MeetTheTeam.vue
  src/pages/courses/[id].vue
Labels: enhancement, ⭐ ALL GOODS WITH THIS UwU ⭐

#98 Titia Hotfix 1 (2)
  src/pages/Discover.vue
  src/pages/topics/[id].vue
Labels: enhancement, ⌛ REVIEWING OwO ⌛

#99 ITECH Phase 2 Final Hotfixes (2)
  package-lock.json
  src/assets/img/unauth/index/section2/slides/HACKER-bg.png
  src/assets/img/unauth/index/section2/slides/HIPSTER-bg.png
  src/assets/img/unauth/index/section2/slides/HUSTLER-bg.png
  src/components/auth/courses/cover.vue
  src/components/auth/courses/coverPlaceholder.vue
  src/components/auth/dashboard/articleEntry.vue
  src/components/auth/dashboard/articlePlaceholder.vue
  src/components/auth/dashboard/coursesPlaceholder.vue
  src/components/auth/dashboard/featureEntry.vue
  src/components/auth/dashboard/playlistEntry.vue
  src/components/unauth/index/section2-slides/Slide.vue
  src/components/unauth/meetTheTeam/teamMemberPlaceholder.vue
  src/components/unauth/unauthBookmarkModal.vue
  src/pages/Categories/Hacker.vue
  src/pages/Categories/Hipster.vue
  src/pages/Categories/Hustler.vue
  src/pages/Dashboard.vue
  src/pages/Discover.vue
  src/pages/Login.vue
  src/pages/MeetTheTeam.vue
  src/pages/courses/[id].vue
  src/pages/topics/[id].vue
Labels: enhancement

#102 nelly Hotfix 3
  src/components/auth/articles/CommentSection.vue
  src/pages/Dashboard.vue
  src/store/modules/articlesStore.js
Labels: enhancement

#103 ITECH Phase 2 Final Hotfixes (3)
  src/components/auth/articles/CommentSection.vue
  src/pages/Dashboard.vue
  src/store/modules/articlesStore.js
Labels: enhancement
